---
language: python
python:
- '2.6'
- '2.7'
before_install:
- pip install pep8
- python setup.py pep8
- sudo apt-get update
- sudo apt-get install libevent-dev
install:
- pip install -r requirements.txt --use-mirrors
- pip install coverage
script: nosetests --with-cover --cover-html --cover-package=decanter
notifications:
  irc: irc.freenode.net#Gengo
after_success: ./scripts/update-gh-pages.sh
env:
  global:
    secure: ! 'jGsBSX8Rex1AzZ9KXHufy/4gUSz/ExiavvnJ+YlpO079m7JRPpE95xAo9CWo

      RgSL6T++CkUfRgMsaUTQ+j/yNJLOL69mvtkG/j6RUD7TzA/MYjDPonqnV5BD

      6oreMX8KB1ubqOSW0AVrfifG7aGxJm4j8xZugqn5tRE2EKm8iP8='
